Entity/MetaFieldRule.php
<?php

/*
 * This file is part of the MetaFieldsBundle for Kimai 2.
 * All rights reserved by Kevin Papst (www.kevinpapst.de).
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace KimaiPlugin\MetaFieldsBundle\Entity;

use App\Entity\Activity;
use App\Entity\Customer;
use App\Entity\Project;
use App\Form\Type\ColorPickerType;
use App\Form\Type\DurationType;
use App\Form\Type\YesNoType;
use Doctrine\ORM\Mapping as ORM;
use KimaiPlugin\MetaFieldsBundle\Form\Type\DatePickerType;
use KimaiPlugin\MetaFieldsBundle\Form\Type\DateTimePickerType;
use KimaiPlugin\MetaFieldsBundle\Form\Type\InvoiceTemplateType;
use KimaiPlugin\MetaFieldsBundle\MetaFieldsRegistry;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\LanguageType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="KimaiPlugin\MetaFieldsBundle\Repository\MetaFieldRuleRepository")
 * @ORM\Table(name="kimai2_meta_field_rules",
 *  uniqueConstraints={
 *      @ORM\UniqueConstraint(name="meta_field_rule_entity_type_name_uniq", columns={"entity_type", "name"})
 *  },
 *  indexes={
 *      @ORM\Index(name="meta_field_rule_entity_type_idx", columns={"entity_type"}),
 *  }
 * )
 * @UniqueEntity({"name", "entityType"})
 * @KimaiPlugin\MetaFieldsBundle\Validator\Constraints\MetaFieldRule
 */
class MetaFieldRule
{
    public const CHOICE_TYPE = 'choice';
    public const CHOICE_TYPE_MULTIPLE = 'choice-multiple';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
    /**
     * @var string
     *
     * @ORM\Column(name="entity_type", type="string", length=100, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=100)
     */
    private $entityType;
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=50, nullable=false)
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Length(min=1, max=50)
     */
    private $name;
    /**
     * @var string
     *
     * @ORM\Column(name="label", type="string", length=50, nullable=true)
     * @Assert\Length(max=50)
     */
    private $label;
    /**
     * @var string
     *
     * @ORM\Column(name="help", type="string", length=200, nullable=true)
     * @Assert\Length(max=200)
     */
    private $help;
    /**
     * @var string
     *
     * @ORM\Column(name="value", type="text", nullable=true)
     */
    private $value;
    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=100, nullable=false)
     * @Assert\NotNull()
     * @Assert\NotBlank()
     * @Assert\Length(max=100)
     */
    private $type;
    /**
     * @var Customer|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $customer;
    /**
     * @var Project|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Project")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $project;
    /**
     * @var Activity|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Activity")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $activity;
    /**
     * @var bool
     *
     * @ORM\Column(name="visible", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $visible = true;
    /**
     * @var bool
     *
     * @ORM\Column(name="required", type="boolean", nullable=false)
     * @Assert\NotNull()
     */
    private $required = false;
    /**
     * @var string
     *
     * @ORM\Column(name="permission", type="string", length=100, nullable=true)
     * @Assert\Length(max=100)
     */
    private $permission = null;
    /**
     * For grouping values in separate sections (currently only supported by user-preferences).
     *
     * @var string|null
     *
     * @ORM\Column(name="section", type="string", length=100, nullable=true)
     * @Assert\Length(max=100)
     */
    private $section = null;
    /**
     * @var int
     *
     * @ORM\Column(name="weight", type="integer", nullable=false, options={"default": 0})
     * @Assert\NotNull()
     */
    private $weight = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isRuleForUser(): bool
    {
        return $this->entityType === MetaFieldsRegistry::USER_ENTITY;
    }

    public function getEntityType(): ?string
    {
        return $this->entityType;
    }

    public function setEntityType(string $entityType): MetaFieldRule
    {
        $this->entityType = $entityType;

        return $this;
    }

    public function isTimesheetRule(): bool
    {
        return $this->entityType === MetaFieldsRegistry::TIMESHEET_ENTITY;
    }

    public function isExpenseRule(): bool
    {
        return $this->entityType === MetaFieldsRegistry::EXPENSE_ENTITY;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): MetaFieldRule
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Only used in the MetaFieldRuleForm.
     * We cannot use getLabel(), as that displays (if unset) the name and doesn't save if it isn't changed.
     *
     * @param string|null $label
     * @return MetaFieldRule
     */
    public function setDisplayName(?string $label): MetaFieldRule
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Only used in the MetaFieldRuleForm.
     * We cannot use getLabel(), as that displays (if unset) the name and doesn't save if it isn't changed.
     *
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return $this->label;
    }

    public function getLabel(): ?string
    {
        if (empty($this->label)) {
            return $this->name;
        }

        return $this->label;
    }

    public function setLabel(string $label): MetaFieldRule
    {
        $this->label = $label;

        return $this;
    }

    public function getHelp(): ?string
    {
        return $this->help;
    }

    public function setHelp(?string $help): MetaFieldRule
    {
        $this->help = $help;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(?string $value): MetaFieldRule
    {
        $this->value = $value;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): MetaFieldRule
    {
        $this->type = $type;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): MetaFieldRule
    {
        $this->customer = $customer;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): MetaFieldRule
    {
        $this->project = $project;

        return $this;
    }

    public function getActivity(): ?Activity
    {
        return $this->activity;
    }

    public function setActivity(?Activity $activity): MetaFieldRule
    {
        $this->activity = $activity;

        return $this;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): MetaFieldRule
    {
        $this->visible = $visible;

        return $this;
    }

    public function isRequired(): bool
    {
        return $this->required;
    }

    public function setRequired(bool $required): MetaFieldRule
    {
        $this->required = $required;

        return $this;
    }

    public function getPermission(): ?string
    {
        return $this->permission;
    }

    public function setPermission(?string $permission): MetaFieldRule
    {
        $this->permission = $permission;

        return $this;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }

    public function setSection(?string $section): MetaFieldRule
    {
        $this->section = $section;

        return $this;
    }

    public function getWeight(): int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): MetaFieldRule
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * USED IN API DEFINITION!
     *
     * @return string
     */
    public function getTypeIdentifier(): string
    {
        $values = explode('\\', $this->entityType);

        return strtolower(array_pop($values));
    }

    public function getMappedFieldType(): ?string
    {
        // before release 1.2 the form type class name was saved in the database
        $type = $this->getType();

        // with >= 1.2 we save only the field alias in the database
        switch ($type) {
            case 'text':
                $type = TextType::class;
                break;
            case 'textarea':
                $type = TextareaType::class;
                break;
            case 'email':
                $type = EmailType::class;
                break;
            case 'integer':

Resources/views/delete.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}

{% block page_title %}{{ 'Meta fields'|trans }}{% endblock %}
{% block page_subtitle %}{{ 'meta_fields.subtitle'|trans }}{% endblock %}
{% block page_actions %}
    {% set actions = {'back': path('custom_meta_fields')} %}
    {% set event = trigger('actions.meta_fields_bundle', {'actions': actions, 'view': 'delete'}) %}
    {{ widgets.page_actions(event.payload.actions) }}
{% endblock %}

{% block main %}

    {% set message = rule.name %}
    {% set inUse = counter > 0 %}
    {% if inUse %}
        {% set message = ("label.deleteRuleInUse"|trans({'%name%': rule.name, '%count%': counter})) %}
    {% endif %}

    {{ include(app.request.xmlHttpRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': message,
        'form': form,
        'used': inUse,
        'back': path('custom_meta_fields')
    }) }}

{% endblock %}

Resources/views/edit.html.twig
{% extends app.request.xmlHttpRequest ? 'form.html.twig' : 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}

{% block page_title %}{{ 'Meta fields'|trans }}{% endblock %}
{% block page_subtitle %}{{ 'meta_fields.subtitle'|trans }}{% endblock %}
{% block page_actions %}
    {% set event = actions(app.user, 'meta_fields_bundle', 'edit') %}
    {{ widgets.page_actions(event.actions) }}
{% endblock %}

{% block main %}
    {% set type = entityType|replace({'App\\Entity\\': '', 'KimaiPlugin\\ExpensesBundle\\Entity\\': ''})|lower %}
    {% set name = 'create'|trans %}
    {% if rule.id %}
        {% set name = rule.label ~ ' (' ~ rule.name ~ ')' %}
    {% endif %}

    {% set title = ('label.' ~ type)|trans %}
    {% if rule.timesheetRule %}
        {% set title = 'menu.admin_timesheet'|trans %}
    {% elseif rule.expenseRule %}
        {% set title = 'Expenses'|trans %}
    {% endif %}

    {% set formEditTemplate = app.request.xmlHttpRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig' %}
    {% set formOptions = {
        'title': title ~ ': ' ~ name,
        'form': form,
        'back': path('custom_meta_fields')
    } %}
    {% embed formEditTemplate with formOptions %}
        {% block form_body %}
            <div class="row">
                <div class="col-md-8">
                    {% if form.name is defined %}
                        {{ form_row(form.name) }}
                    {% endif %}
                </div>
                <div class="col-md-4">
                    {% if form.type is defined %}
                        {{ form_row(form.type) }}
                    {% endif %}
                </div>
            </div>
            {{ form_row(form.displayName) }}
            {{ form_row(form.help) }}
            {{ form_row(form.value) }}
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.required) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.visible) }}
                </div>
            </div>
            <div class="row">
                <div class="{% if form.section is defined %}col-md-6{% else %}col-md-12{% endif %}">
                    {{ form_row(form.weight) }}
                </div>
                {% if form.section is defined %}
                <div class="col-md-6">
                    {{ form_row(form.section) }}
                </div>
                {% endif %}
            </div>

            <fieldset>
                <legend>{{ 'meta_fields.visibility'|trans }}</legend>
                {% set cols = 0 %}
                {% if form.customer is defined %}
                    {% set cols = cols + 1 %}
                {% endif %}
                {% if form.project is defined %}
                    {% set cols = cols + 1 %}
                {% endif %}
                {% if form.activity is defined %}
                    {% set cols = cols + 1 %}
                {% endif %}
                {% set colLength = 0 %}
                {% if cols == 1 %}
                    {% set colLength = 12 %}
                {% elseif cols == 2 %}
                    {% set colLength = 6 %}
                {% elseif cols == 3 %}
                    {% set colLength = 4 %}
                {% endif %}
                <div class="row">
                    {% if form.customer is defined %}
                        <div class="col-md-{{ colLength }}">
                            {{ form_row(form.customer) }}
                        </div>
                    {% endif %}
                    {% if form.project is defined %}
                        <div class="col-md-{{ colLength }}">
                            {{ form_row(form.project) }}
                        </div>
                    {% endif %}
                    {% if form.activity is defined %}
                        <div class="col-md-{{ colLength }}">
                            {{ form_row(form.activity) }}
                        </div>
                    {% endif %}
                </div>

                {{ form_row(form.permission) }}
            </fieldset>

            {{ form_widget(form) }}
        {% endblock %}
    {% endembed %}

{% endblock %}

Resources/views/index.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/widgets.html.twig' as widgets %}
{% import "macros/datatables.html.twig" as tables %}

{% set columns = {
    'label': {'class': 'alwaysVisible', 'title': 'label.name'|trans, 'orderBy': false},
    'key': {'class': 'hidden-xs', 'orderBy': false},
    'inputType': {'class': 'hidden-xs', 'title': 'label.mf_inputType'|trans, 'orderBy': false},
    'defaultValue': {'class': 'hidden', 'title': 'label.defaultValue'|trans, 'orderBy': false},
    'appliesTo': {'class': 'hidden', 'title': 'label.applies_to'|trans, 'orderBy': false},
    'required': {'class': 'text-center hidden-xs w-min', 'title': 'label.mf_required'|trans, 'orderBy': false},
    'visible': {'class': 'text-center w-min', 'orderBy': false},
    'actions': {'class': 'actions alwaysVisible w-min', 'orderBy': false}
} %}

{% set tableName = 'meta_fields_admin' %}

{% block page_title %}{{ 'Meta fields'|trans }}{% endblock %}
{% block page_subtitle %}{{ 'meta_fields.subtitle'|trans }}{% endblock %}
{% block page_actions %}
    {% set event = actions(app.user, 'meta_fields_bundle', 'index') %}
    {{ widgets.page_actions(event.actions) }}
{% endblock %}

{% block main_before %}
    {{ tables.data_table_column_modal(tableName, columns) }}
{% endblock %}

{% block main %}

    {% for type, config in types %}
        {% embed '@AdminLTE/Widgets/box-widget.html.twig' with {boxtype: 'default', 'type': config.type, 'rules': config.rules, 'title': config.title, 'columns': columns, 'tableName': tableName} only %}
            {% import 'macros/widgets.html.twig' as widgets %}
            {% block box_title %}{{ title|trans }}{% endblock %}
            {% block box_tools %}
                {% set actions = {'create': {'url': path('custom_meta_fields_create', {'entityType': type}), 'class': 'modal-ajax-form btn-sm'}} %}
                {{ widgets.button_group(actions) }}
            {% endblock %}
            {% block box_body_class %}{% if rules is not empty %}no-padding{% endif %}{% endblock %}
            {% block box_body %}
                {% if rules is empty %}
                    {{ widgets.callout('info', 'meta_fields.no_rules') }}
                {% else %}
                    {% import 'macros/widgets.html.twig' as widgets %}
                    {% import "macros/datatables.html.twig" as tables %}
                    {{ tables.datatable_header(tableName, columns, null, {'boxClass': ''}) }}
                    {% for rule in rules %}
                        <tr class="modal-ajax-form open-edit" data-href="{{ path('custom_meta_fields_edit', {'id' : rule.id}) }}">
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'label') }}">{{ rule.label }}</td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'key') }}">{{ rule.name }}</td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'inputType') }}">{{ rule.type|form_field_type }}</td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'defaultValue') }}">
                                {% if rule.type == 'boolean' %}
                                    {{ widgets.label_boolean(rule.value) }}
                                {% elseif rule.type == 'date' and rule.value is not empty %}
                                    {{ rule.value|date_short }}
                                {% elseif rule.type == 'datetime' and rule.value is not empty %}
                                    {{ rule.value|date_full }}
                                {% else %}
                                    {{ rule.value }}
                                {% endif %}
                            </td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'appliesTo') }}">
                                {% if not rule.customer is null or not rule.project is null or not rule.activity is null %}
                                    {% if not rule.customer is null %}
                                        {{ widgets.label_customer(rule.customer) }}<br>
                                    {% endif %}
                                    {% if not rule.project is null %}
                                        {{ widgets.label_project(rule.project) }}<br>
                                    {% endif %}
                                    {% if not rule.activity is null %}
                                        {{ widgets.label_activity(rule.activity) }}
                                    {% endif %}
                                {% else %}
                                    {{ widgets.label('label.apply_all'|trans, 'success') }}
                                {% endif %}
                            </td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'required') }}">{{ widgets.label_boolean(rule.required) }}</td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'visible') }}">{{ widgets.label_visible(rule.visible) }}</td>
                            <td class="{{ tables.data_table_column_class(tableName, columns, 'actions') }}">
                                {% set actions = {
                                    'edit': {'url': path('custom_meta_fields_edit', {'id' : rule.id}), 'class': 'modal-ajax-form'},
                                    'trash': {'url': path('custom_meta_fields_delete', {'id': rule.id}), 'class': 'modal-ajax-form'}
                                } %}

                                {% set event = trigger('actions.meta_field_bundle_rule', {'actions': actions, 'view': 'index', 'rule': rule}) %}
                                {{ widgets.table_actions(event.payload.actions) }}
                            </td>
                        </tr>
                    {% endfor %}
                    {{ tables.data_table_footer(rules, null) }}
                {% endif %}
            {% endblock %}
        {% endembed %}
    {% endfor %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.metaFieldRuleUpdate');
        });
    </script>
{% endblock %}